# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run docs:build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: deploy
        FOLDER: dist
      # 上传打包文件到远程服务器
    - name: 上传文件到远程服务器
      uses: zhenyuWang/Upload-File-Action@v1.0.1
      with:
        username: ${{ secrets.SSH_HOST }}
        server: ${{ secrets.SSH_USERNAME }}
        port: "22"
        ssh_private_key: ${{ secrets.DEPLOY_KEY}}
        # 要上传文件所在目录
        local_path: "./dist/*"
        # 远程服务器目标路径
        target_path: "/usr/local/nginx/html/xxx"
